"Type: Feature":
  - head-branch: [ '^feat', '-feature-' ]
"Type: Bug":
  - head-branch: [ '^bug', '-bug-' ]
"Template: personalization-service":
  - changed-files:
      - any-glob-to-any-file: [ 'personalization-service/**' ]
"Component: ticketing-eai":
  - changed-files:
      - any-glob-to-any-file: [ 'ticketing-eai/**' ]
"Component: ticketing-eventing":
  - changed-files:
      - any-glob-to-any-file: [ 'ticketing-eventing/**' ]
