# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
tone_instructions: "Friendly, thankful and supportive."
reviews:
  profile: "chill"
  review_status: true
  auto_review:
    enabled: false
  tools:
    pmd:
      enabled: false
    eslint:
      enabled: false
  finishing_touches:
    docstrings:
      enabled: false # needs to be disabled as it collides with the PR require checklist functionality (workflow in .github/workflows/pr-checklist.yml)
chat:
  auto_reply: true
  
