server:
  port: 8084
spring:
  security:
    user:
      password: "password"

# Enable swagger-ui
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  structured:
    format:
      console: # set to empty to disable structured logging locally
  level:
    root: INFO
    de.muenchen.refarch: DEBUG
    org.springframework.cache: TRACE
    org.springframework.web: DEBUG

refarch:
  security:
    logging-mode: all
