/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {Link} from "../models/Link";
import * as runtime from "../runtime";

export interface ScrapeRequest {
  format?: ScrapeFormatEnum;
  includedNames?: string;
}

/**
 *
 */
export class ActuatorApi extends runtime.BaseAPI {
  /**
   * Creates request options for health without sending the request
   */
  async healthRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/actuator/health`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Actuator web endpoint \'health\'
   */
  async healthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<object>> {
    const requestOptions = await this.healthRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Actuator web endpoint \'health\'
   */
  async health(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<object> {
    const response = await this.healthRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for info without sending the request
   */
  async infoRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/actuator/info`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Actuator web endpoint \'info\'
   */
  async infoRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<object>> {
    const requestOptions = await this.infoRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Actuator web endpoint \'info\'
   */
  async info(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<object> {
    const response = await this.infoRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for links without sending the request
   */
  async linksRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/actuator`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Actuator root web endpoint
   */
  async linksRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<{ [key: string]: { [key: string]: Link } }>> {
    const requestOptions = await this.linksRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Actuator root web endpoint
   */
  async links(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<{ [key: string]: { [key: string]: Link } }> {
    const response = await this.linksRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for scrape without sending the request
   */
  async scrapeRequestOpts(
    requestParameters: ScrapeRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["format"] != null) {
      queryParameters["format"] = requestParameters["format"];
    }

    if (requestParameters["includedNames"] != null) {
      queryParameters["includedNames"] = requestParameters["includedNames"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/actuator/metrics`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Actuator web endpoint \'prometheus\'
   */
  async scrapeRaw(
    requestParameters: ScrapeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<object>> {
    const requestOptions = await this.scrapeRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Actuator web endpoint \'prometheus\'
   */
  async scrape(
    requestParameters: ScrapeRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<object> {
    const response = await this.scrapeRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const ScrapeFormatEnum = {
  ContentType004: "CONTENT_TYPE_004",
  ContentTypeOpenmetrics100: "CONTENT_TYPE_OPENMETRICS_100",
  ContentTypeProtobuf: "CONTENT_TYPE_PROTOBUF",
} as const;
export type ScrapeFormatEnum =
  (typeof ScrapeFormatEnum)[keyof typeof ScrapeFormatEnum];
