/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ChecklistCreateDTO } from "../models/ChecklistCreateDTO";
import type { ChecklistReadDTO } from "../models/ChecklistReadDTO";
import type { ChecklistServiceNavigatorReadDTO } from "../models/ChecklistServiceNavigatorReadDTO";
import type { ChecklistUpdateDTO } from "../models/ChecklistUpdateDTO";

import {
  ChecklistCreateDTOFromJSON,
  ChecklistCreateDTOToJSON,
} from "../models/ChecklistCreateDTO";
import {
  ChecklistReadDTOFromJSON,
  ChecklistReadDTOToJSON,
} from "../models/ChecklistReadDTO";
import {
  ChecklistServiceNavigatorReadDTOFromJSON,
  ChecklistServiceNavigatorReadDTOToJSON,
} from "../models/ChecklistServiceNavigatorReadDTO";
import {
  ChecklistUpdateDTOFromJSON,
  ChecklistUpdateDTOToJSON,
} from "../models/ChecklistUpdateDTO";
import * as runtime from "../runtime";

export interface CheckChecklistEntryRequest {
  checklistID: string;
  serviceID: string;
}

export interface CreateChecklistRequest {
  checklistCreateDTO: ChecklistCreateDTO;
}

export interface DeleteChecklistRequest {
  checklistID: string;
}

export interface GetChecklistRequest {
  checklistID: string;
}

export interface UncheckChecklistEntryRequest {
  checklistID: string;
  serviceID: string;
}

export interface UpdateChecklistRequest {
  checklistID: string;
  checklistUpdateDTO: ChecklistUpdateDTO;
}

/**
 *
 */
export class ChecklistsApi extends runtime.BaseAPI {
  /**
   * Creates request options for checkChecklistEntry without sending the request
   */
  async checkChecklistEntryRequestOpts(
    requestParameters: CheckChecklistEntryRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["checklistID"] == null) {
      throw new runtime.RequiredError(
        "checklistID",
        'Required parameter "checklistID" was null or undefined when calling checkChecklistEntry().'
      );
    }

    if (requestParameters["serviceID"] == null) {
      throw new runtime.RequiredError(
        "serviceID",
        'Required parameter "serviceID" was null or undefined when calling checkChecklistEntry().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/checklist/{checklistID}/{serviceID}/check`;
    urlPath = urlPath.replace(
      "{checklistID}",
      encodeURIComponent(String(requestParameters["checklistID"]))
    );
    urlPath = urlPath.replace(
      "{serviceID}",
      encodeURIComponent(String(requestParameters["serviceID"]))
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Checks a checklist-entry.
   * Check a Checklist-Entry
   */
  async checkChecklistEntryRaw(
    requestParameters: CheckChecklistEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChecklistServiceNavigatorReadDTO>> {
    const requestOptions =
      await this.checkChecklistEntryRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChecklistServiceNavigatorReadDTOFromJSON(jsonValue)
    );
  }

  /**
   * Checks a checklist-entry.
   * Check a Checklist-Entry
   */
  async checkChecklistEntry(
    requestParameters: CheckChecklistEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChecklistServiceNavigatorReadDTO> {
    const response = await this.checkChecklistEntryRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for createChecklist without sending the request
   */
  async createChecklistRequestOpts(
    requestParameters: CreateChecklistRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["checklistCreateDTO"] == null) {
      throw new runtime.RequiredError(
        "checklistCreateDTO",
        'Required parameter "checklistCreateDTO" was null or undefined when calling createChecklist().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/checklist`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ChecklistCreateDTOToJSON(requestParameters["checklistCreateDTO"]),
    };
  }

  /**
   * Creates a new checklist using the provided checklist details.
   * Create a new checklist
   */
  async createChecklistRaw(
    requestParameters: CreateChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChecklistReadDTO>> {
    const requestOptions =
      await this.createChecklistRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChecklistReadDTOFromJSON(jsonValue)
    );
  }

  /**
   * Creates a new checklist using the provided checklist details.
   * Create a new checklist
   */
  async createChecklist(
    requestParameters: CreateChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChecklistReadDTO> {
    const response = await this.createChecklistRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for deleteChecklist without sending the request
   */
  async deleteChecklistRequestOpts(
    requestParameters: DeleteChecklistRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["checklistID"] == null) {
      throw new runtime.RequiredError(
        "checklistID",
        'Required parameter "checklistID" was null or undefined when calling deleteChecklist().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/checklist/{checklistID}`;
    urlPath = urlPath.replace(
      "{checklistID}",
      encodeURIComponent(String(requestParameters["checklistID"]))
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Deletes a checklist by checklistId.
   * Delete a checklist
   */
  async deleteChecklistRaw(
    requestParameters: DeleteChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.deleteChecklistRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Deletes a checklist by checklistId.
   * Delete a checklist
   */
  async deleteChecklist(
    requestParameters: DeleteChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteChecklistRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getChecklist without sending the request
   */
  async getChecklistRequestOpts(
    requestParameters: GetChecklistRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["checklistID"] == null) {
      throw new runtime.RequiredError(
        "checklistID",
        'Required parameter "checklistID" was null or undefined when calling getChecklist().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/checklist/{checklistID}`;
    urlPath = urlPath.replace(
      "{checklistID}",
      encodeURIComponent(String(requestParameters["checklistID"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a checklist by checklistId
   * Get specific checklist by checklist-id.
   */
  async getChecklistRaw(
    requestParameters: GetChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChecklistServiceNavigatorReadDTO>> {
    const requestOptions =
      await this.getChecklistRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChecklistServiceNavigatorReadDTOFromJSON(jsonValue)
    );
  }

  /**
   * Returns a checklist by checklistId
   * Get specific checklist by checklist-id.
   */
  async getChecklist(
    requestParameters: GetChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChecklistServiceNavigatorReadDTO> {
    const response = await this.getChecklistRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for getChecklists without sending the request
   */
  async getChecklistsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/checklist`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all checklists of an user (identified by JWT-Token)
   * Get all checklists by user.
   */
  async getChecklistsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<ChecklistReadDTO>>> {
    const requestOptions = await this.getChecklistsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ChecklistReadDTOFromJSON)
    );
  }

  /**
   * Returns all checklists of an user (identified by JWT-Token)
   * Get all checklists by user.
   */
  async getChecklists(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<ChecklistReadDTO>> {
    const response = await this.getChecklistsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for uncheckChecklistEntry without sending the request
   */
  async uncheckChecklistEntryRequestOpts(
    requestParameters: UncheckChecklistEntryRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["checklistID"] == null) {
      throw new runtime.RequiredError(
        "checklistID",
        'Required parameter "checklistID" was null or undefined when calling uncheckChecklistEntry().'
      );
    }

    if (requestParameters["serviceID"] == null) {
      throw new runtime.RequiredError(
        "serviceID",
        'Required parameter "serviceID" was null or undefined when calling uncheckChecklistEntry().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/checklist/{checklistID}/{serviceID}/uncheck`;
    urlPath = urlPath.replace(
      "{checklistID}",
      encodeURIComponent(String(requestParameters["checklistID"]))
    );
    urlPath = urlPath.replace(
      "{serviceID}",
      encodeURIComponent(String(requestParameters["serviceID"]))
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Unchecks a checklist-entry.
   * Uncheck a Checklist-Entry
   */
  async uncheckChecklistEntryRaw(
    requestParameters: UncheckChecklistEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChecklistServiceNavigatorReadDTO>> {
    const requestOptions =
      await this.uncheckChecklistEntryRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChecklistServiceNavigatorReadDTOFromJSON(jsonValue)
    );
  }

  /**
   * Unchecks a checklist-entry.
   * Uncheck a Checklist-Entry
   */
  async uncheckChecklistEntry(
    requestParameters: UncheckChecklistEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChecklistServiceNavigatorReadDTO> {
    const response = await this.uncheckChecklistEntryRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for updateChecklist without sending the request
   */
  async updateChecklistRequestOpts(
    requestParameters: UpdateChecklistRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["checklistID"] == null) {
      throw new runtime.RequiredError(
        "checklistID",
        'Required parameter "checklistID" was null or undefined when calling updateChecklist().'
      );
    }

    if (requestParameters["checklistUpdateDTO"] == null) {
      throw new runtime.RequiredError(
        "checklistUpdateDTO",
        'Required parameter "checklistUpdateDTO" was null or undefined when calling updateChecklist().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/checklist/{checklistID}`;
    urlPath = urlPath.replace(
      "{checklistID}",
      encodeURIComponent(String(requestParameters["checklistID"]))
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: ChecklistUpdateDTOToJSON(requestParameters["checklistUpdateDTO"]),
    };
  }

  /**
   * Updates a checklist using the provided checklist details.
   * Update a checklist
   */
  async updateChecklistRaw(
    requestParameters: UpdateChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChecklistServiceNavigatorReadDTO>> {
    const requestOptions =
      await this.updateChecklistRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChecklistServiceNavigatorReadDTOFromJSON(jsonValue)
    );
  }

  /**
   * Updates a checklist using the provided checklist details.
   * Update a checklist
   */
  async updateChecklist(
    requestParameters: UpdateChecklistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChecklistServiceNavigatorReadDTO> {
    const response = await this.updateChecklistRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
