/* tslint:disable */
/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChecklistItemServiceNavigatorDTO,
    ChecklistItemServiceNavigatorDTOFromJSON,
    ChecklistItemServiceNavigatorDTOToJSON,
} from '../models/ChecklistItemServiceNavigatorDTO';

export interface GetServicesByIdsRequest {
    ids: string;
    lang?: string;
}

/**
 * 
 */
export class PublicServiceNavigatorEndpointsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getServicesByIds without sending the request
     */
    async getServicesByIdsRequestOpts(requestParameters: GetServicesByIdsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ids'] == null) {
            throw new runtime.RequiredError(
                'ids',
                'Required parameter "ids" was null or undefined when calling getServicesByIds().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/servicenavigator`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lookup ServiceNavigator Services by ServiceID. Returns a list of services for the given service IDs.
     */
    async getServicesByIdsRaw(requestParameters: GetServicesByIdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChecklistItemServiceNavigatorDTO>>> {
        const requestOptions = await this.getServicesByIdsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChecklistItemServiceNavigatorDTOFromJSON));
    }

    /**
     * Lookup ServiceNavigator Services by ServiceID. Returns a list of services for the given service IDs.
     */
    async getServicesByIds(requestParameters: GetServicesByIdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChecklistItemServiceNavigatorDTO>> {
        const response = await this.getServicesByIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
