/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ChecklistItemDTO } from "./ChecklistItemDTO";

import { mapValues } from "../runtime";
import {
  ChecklistItemDTOFromJSON,
  ChecklistItemDTOFromJSONTyped,
  ChecklistItemDTOToJSON,
  ChecklistItemDTOToJSONTyped,
} from "./ChecklistItemDTO";

/**
 *
 * @export
 * @interface ChecklistReadDTO
 */
export interface ChecklistReadDTO {
  /**
   *
   * @type {string}
   * @memberof ChecklistReadDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistReadDTO
   */
  lhmExtId: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistReadDTO
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistReadDTO
   */
  situationId?: string;
  /**
   *
   * @type {Date}
   * @memberof ChecklistReadDTO
   */
  lastUpdate: Date;
  /**
   *
   * @type {Array<ChecklistItemDTO>}
   * @memberof ChecklistReadDTO
   */
  checklistItems: Array<ChecklistItemDTO>;
}

/**
 * Check if a given object implements the ChecklistReadDTO interface.
 */
export function instanceOfChecklistReadDTO(
  value: object
): value is ChecklistReadDTO {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("lhmExtId" in value) || value["lhmExtId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("lastUpdate" in value) || value["lastUpdate"] === undefined)
    return false;
  if (!("checklistItems" in value) || value["checklistItems"] === undefined)
    return false;
  return true;
}

export function ChecklistReadDTOFromJSON(json: any): ChecklistReadDTO {
  return ChecklistReadDTOFromJSONTyped(json, false);
}

export function ChecklistReadDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChecklistReadDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    lhmExtId: json["lhmExtId"],
    title: json["title"],
    situationId: json["situationId"] == null ? undefined : json["situationId"],
    lastUpdate: new Date(json["lastUpdate"]),
    checklistItems: (json["checklistItems"] as Array<any>).map(
      ChecklistItemDTOFromJSON
    ),
  };
}

export function ChecklistReadDTOToJSON(json: any): ChecklistReadDTO {
  return ChecklistReadDTOToJSONTyped(json, false);
}

export function ChecklistReadDTOToJSONTyped(
  value?: ChecklistReadDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    lhmExtId: value["lhmExtId"],
    title: value["title"],
    situationId: value["situationId"],
    lastUpdate: value["lastUpdate"].toISOString(),
    checklistItems: (value["checklistItems"] as Array<any>).map(
      ChecklistItemDTOToJSON
    ),
  };
}
