/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {ChecklistItemDTO} from "./ChecklistItemDTO";
import {ChecklistItemDTOFromJSON, ChecklistItemDTOToJSON,} from "./ChecklistItemDTO";

/**
 *
 * @export
 * @interface ChecklistCreateDTO
 */
export interface ChecklistCreateDTO {
  /**
   *
   * @type {string}
   * @memberof ChecklistCreateDTO
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistCreateDTO
   */
  situationId?: string;
  /**
   *
   * @type {Array<ChecklistItemDTO>}
   * @memberof ChecklistCreateDTO
   */
  checklistItems: Array<ChecklistItemDTO>;
}

/**
 * Check if a given object implements the ChecklistCreateDTO interface.
 */
export function instanceOfChecklistCreateDTO(
  value: object
): value is ChecklistCreateDTO {
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("checklistItems" in value) || value["checklistItems"] === undefined)
    return false;
  return true;
}

export function ChecklistCreateDTOFromJSON(json: any): ChecklistCreateDTO {
  return ChecklistCreateDTOFromJSONTyped(json, false);
}

export function ChecklistCreateDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChecklistCreateDTO {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
    situationId: json["situationId"] == null ? undefined : json["situationId"],
    checklistItems: (json["checklistItems"] as Array<any>).map(
      ChecklistItemDTOFromJSON
    ),
  };
}

export function ChecklistCreateDTOToJSON(json: any): ChecklistCreateDTO {
  return ChecklistCreateDTOToJSONTyped(json, false);
}

export function ChecklistCreateDTOToJSONTyped(
  value?: ChecklistCreateDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    situationId: value["situationId"],
    checklistItems: (value["checklistItems"] as Array<any>).map(
      ChecklistItemDTOToJSON
    ),
  };
}
