/* tslint:disable */
/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChecklistItemDTO } from './ChecklistItemDTO';
import {
    ChecklistItemDTOFromJSON,
    ChecklistItemDTOFromJSONTyped,
    ChecklistItemDTOToJSON,
    ChecklistItemDTOToJSONTyped,
} from './ChecklistItemDTO';

/**
 * 
 * @export
 * @interface ChecklistUpdateDTO
 */
export interface ChecklistUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ChecklistUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChecklistUpdateDTO
     */
    lhmExtId: string;
    /**
     * 
     * @type {string}
     * @memberof ChecklistUpdateDTO
     */
    title: string;
    /**
     * 
     * @type {Array<ChecklistItemDTO>}
     * @memberof ChecklistUpdateDTO
     */
    checklistItems: Array<ChecklistItemDTO>;
}

/**
 * Check if a given object implements the ChecklistUpdateDTO interface.
 */
export function instanceOfChecklistUpdateDTO(value: object): value is ChecklistUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lhmExtId' in value) || value['lhmExtId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('checklistItems' in value) || value['checklistItems'] === undefined) return false;
    return true;
}

export function ChecklistUpdateDTOFromJSON(json: any): ChecklistUpdateDTO {
    return ChecklistUpdateDTOFromJSONTyped(json, false);
}

export function ChecklistUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChecklistUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lhmExtId': json['lhmExtId'],
        'title': json['title'],
        'checklistItems': ((json['checklistItems'] as Array<any>).map(ChecklistItemDTOFromJSON)),
    };
}

export function ChecklistUpdateDTOToJSON(json: any): ChecklistUpdateDTO {
    return ChecklistUpdateDTOToJSONTyped(json, false);
}

export function ChecklistUpdateDTOToJSONTyped(value?: ChecklistUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lhmExtId': value['lhmExtId'],
        'title': value['title'],
        'checklistItems': ((value['checklistItems'] as Array<any>).map(ChecklistItemDTOToJSON)),
    };
}

