/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OnlineServiceDTO } from "./OnlineServiceDTO";

import { mapValues } from "../runtime";
import {
  OnlineServiceDTOFromJSON,
  OnlineServiceDTOFromJSONTyped,
  OnlineServiceDTOToJSON,
  OnlineServiceDTOToJSONTyped,
} from "./OnlineServiceDTO";

/**
 *
 * @export
 * @interface ChecklistItemServiceNavigatorDTO
 */
export interface ChecklistItemServiceNavigatorDTO {
  /**
   *
   * @type {string}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  serviceID?: string;
  /**
   *
   * @type {Date}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  checked?: Date;
  /**
   *
   * @type {string}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  publicUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  note?: string;
  /**
   *
   * @type {boolean}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  isExternal?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  required?: boolean;
  /**
   *
   * @type {string}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  appointmentServiceUrl?: string;
  /**
   *
   * @type {boolean}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  appointmentService?: boolean;
  /**
   *
   * @type {Array<OnlineServiceDTO>}
   * @memberof ChecklistItemServiceNavigatorDTO
   */
  onlineServices?: Array<OnlineServiceDTO>;
}

/**
 * Check if a given object implements the ChecklistItemServiceNavigatorDTO interface.
 */
export function instanceOfChecklistItemServiceNavigatorDTO(
  value: object
): value is ChecklistItemServiceNavigatorDTO {
  return true;
}

export function ChecklistItemServiceNavigatorDTOFromJSON(
  json: any
): ChecklistItemServiceNavigatorDTO {
  return ChecklistItemServiceNavigatorDTOFromJSONTyped(json, false);
}

export function ChecklistItemServiceNavigatorDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChecklistItemServiceNavigatorDTO {
  if (json == null) {
    return json;
  }
  return {
    serviceID: json["serviceID"] == null ? undefined : json["serviceID"],
    checked: json["checked"] == null ? undefined : new Date(json["checked"]),
    title: json["title"] == null ? undefined : json["title"],
    publicUrl: json["publicUrl"] == null ? undefined : json["publicUrl"],
    note: json["note"] == null ? undefined : json["note"],
    isExternal: json["isExternal"] == null ? undefined : json["isExternal"],
    required: json["required"] == null ? undefined : json["required"],
    appointmentServiceUrl:
      json["appointmentServiceUrl"] == null
        ? undefined
        : json["appointmentServiceUrl"],
    appointmentService:
      json["appointmentService"] == null
        ? undefined
        : json["appointmentService"],
    onlineServices:
      json["onlineServices"] == null
        ? undefined
        : (json["onlineServices"] as Array<any>).map(OnlineServiceDTOFromJSON),
  };
}

export function ChecklistItemServiceNavigatorDTOToJSON(
  json: any
): ChecklistItemServiceNavigatorDTO {
  return ChecklistItemServiceNavigatorDTOToJSONTyped(json, false);
}

export function ChecklistItemServiceNavigatorDTOToJSONTyped(
  value?: ChecklistItemServiceNavigatorDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    serviceID: value["serviceID"],
    checked:
      value["checked"] == null
        ? value["checked"]
        : value["checked"].toISOString(),
    title: value["title"],
    publicUrl: value["publicUrl"],
    note: value["note"],
    isExternal: value["isExternal"],
    required: value["required"],
    appointmentServiceUrl: value["appointmentServiceUrl"],
    appointmentService: value["appointmentService"],
    onlineServices:
      value["onlineServices"] == null
        ? undefined
        : (value["onlineServices"] as Array<any>).map(OnlineServiceDTOToJSON),
  };
}
