/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChecklistItemDTO
 */
export interface ChecklistItemDTO {
  /**
   *
   * @type {string}
   * @memberof ChecklistItemDTO
   */
  serviceID?: string;
  /**
   *
   * @type {Date}
   * @memberof ChecklistItemDTO
   */
  checked?: Date;
  /**
   *
   * @type {string}
   * @memberof ChecklistItemDTO
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistItemDTO
   */
  note?: string;
  /**
   *
   * @type {boolean}
   * @memberof ChecklistItemDTO
   */
  required?: boolean;
}

/**
 * Check if a given object implements the ChecklistItemDTO interface.
 */
export function instanceOfChecklistItemDTO(
  value: object
): value is ChecklistItemDTO {
  return true;
}

export function ChecklistItemDTOFromJSON(json: any): ChecklistItemDTO {
  return ChecklistItemDTOFromJSONTyped(json, false);
}

export function ChecklistItemDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChecklistItemDTO {
  if (json == null) {
    return json;
  }
  return {
    serviceID: json["serviceID"] == null ? undefined : json["serviceID"],
    checked: json["checked"] == null ? undefined : new Date(json["checked"]),
    title: json["title"] == null ? undefined : json["title"],
    note: json["note"] == null ? undefined : json["note"],
    required: json["required"] == null ? undefined : json["required"],
  };
}

export function ChecklistItemDTOToJSON(json: any): ChecklistItemDTO {
  return ChecklistItemDTOToJSONTyped(json, false);
}

export function ChecklistItemDTOToJSONTyped(
  value?: ChecklistItemDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    serviceID: value["serviceID"],
    checked:
      value["checked"] == null
        ? value["checked"]
        : value["checked"].toISOString(),
    title: value["title"],
    note: value["note"],
    required: value["required"],
  };
}
