/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {ChecklistItemServiceNavigatorDTO} from "./ChecklistItemServiceNavigatorDTO";
import {
    ChecklistItemServiceNavigatorDTOFromJSON,
    ChecklistItemServiceNavigatorDTOToJSON,
} from "./ChecklistItemServiceNavigatorDTO";

/**
 *
 * @export
 * @interface ChecklistServiceNavigatorReadDTO
 */
export interface ChecklistServiceNavigatorReadDTO {
  /**
   *
   * @type {string}
   * @memberof ChecklistServiceNavigatorReadDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistServiceNavigatorReadDTO
   */
  lhmExtId?: string;
  /**
   *
   * @type {string}
   * @memberof ChecklistServiceNavigatorReadDTO
   */
  title?: string;
  /**
   *
   * @type {Date}
   * @memberof ChecklistServiceNavigatorReadDTO
   */
  lastUpdate?: Date;
  /**
   *
   * @type {string}
   * @memberof ChecklistServiceNavigatorReadDTO
   */
  situationId?: string;
  /**
   *
   * @type {Array<ChecklistItemServiceNavigatorDTO>}
   * @memberof ChecklistServiceNavigatorReadDTO
   */
  checklistItemServiceNavigatorDtos?: Array<ChecklistItemServiceNavigatorDTO>;
}

/**
 * Check if a given object implements the ChecklistServiceNavigatorReadDTO interface.
 */
export function instanceOfChecklistServiceNavigatorReadDTO(
  value: object
): value is ChecklistServiceNavigatorReadDTO {
  return true;
}

export function ChecklistServiceNavigatorReadDTOFromJSON(
  json: any
): ChecklistServiceNavigatorReadDTO {
  return ChecklistServiceNavigatorReadDTOFromJSONTyped(json, false);
}

export function ChecklistServiceNavigatorReadDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChecklistServiceNavigatorReadDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    lhmExtId: json["lhmExtId"] == null ? undefined : json["lhmExtId"],
    title: json["title"] == null ? undefined : json["title"],
    lastUpdate:
      json["lastUpdate"] == null ? undefined : new Date(json["lastUpdate"]),
    situationId: json["situationId"] == null ? undefined : json["situationId"],
    checklistItemServiceNavigatorDtos:
      json["checklistItemServiceNavigatorDtos"] == null
        ? undefined
        : (json["checklistItemServiceNavigatorDtos"] as Array<any>).map(
            ChecklistItemServiceNavigatorDTOFromJSON
          ),
  };
}

export function ChecklistServiceNavigatorReadDTOToJSON(
  json: any
): ChecklistServiceNavigatorReadDTO {
  return ChecklistServiceNavigatorReadDTOToJSONTyped(json, false);
}

export function ChecklistServiceNavigatorReadDTOToJSONTyped(
  value?: ChecklistServiceNavigatorReadDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    lhmExtId: value["lhmExtId"],
    title: value["title"],
    lastUpdate:
      value["lastUpdate"] == null
        ? value["lastUpdate"]
        : value["lastUpdate"].toISOString(),
    situationId: value["situationId"],
    checklistItemServiceNavigatorDtos:
      value["checklistItemServiceNavigatorDtos"] == null
        ? undefined
        : (value["checklistItemServiceNavigatorDtos"] as Array<any>).map(
            ChecklistItemServiceNavigatorDTOToJSON
          ),
  };
}
