/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Link
 */
export interface Link {
  /**
   *
   * @type {string}
   * @memberof Link
   */
  href?: string;
  /**
   *
   * @type {boolean}
   * @memberof Link
   */
  templated?: boolean;
}

/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): value is Link {
  return true;
}

export function LinkFromJSON(json: any): Link {
  return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Link {
  if (json == null) {
    return json;
  }
  return {
    href: json["href"] == null ? undefined : json["href"],
    templated: json["templated"] == null ? undefined : json["templated"],
  };
}

export function LinkToJSON(json: any): Link {
  return LinkToJSONTyped(json, false);
}

export function LinkToJSONTyped(
  value?: Link | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    href: value["href"],
    templated: value["templated"],
  };
}
