/* eslint-disable */
/**
 * personalization-service
 * Personalization service for the digital citizen service of the City of Munich
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface OnlineServiceDTO
 */
export interface OnlineServiceDTO {
  /**
   *
   * @type {string}
   * @memberof OnlineServiceDTO
   */
  uri?: string;
  /**
   *
   * @type {string}
   * @memberof OnlineServiceDTO
   */
  label?: string;
}

/**
 * Check if a given object implements the OnlineServiceDTO interface.
 */
export function instanceOfOnlineServiceDTO(
  value: object
): value is OnlineServiceDTO {
  return true;
}

export function OnlineServiceDTOFromJSON(json: any): OnlineServiceDTO {
  return OnlineServiceDTOFromJSONTyped(json, false);
}

export function OnlineServiceDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OnlineServiceDTO {
  if (json == null) {
    return json;
  }
  return {
    uri: json["uri"] == null ? undefined : json["uri"],
    label: json["label"] == null ? undefined : json["label"],
  };
}

export function OnlineServiceDTOToJSON(json: any): OnlineServiceDTO {
  return OnlineServiceDTOToJSONTyped(json, false);
}

export function OnlineServiceDTOToJSONTyped(
  value?: OnlineServiceDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    uri: value["uri"],
    label: value["label"],
  };
}
